mode = "dark"

accent = "#549235"
selection = "#315520"
muted = "#9E9E9E"

background = "#1f1d45"
dark_background = "#29274a"
darker_background = "#1c1a3e"
lighter_background = "#36345f"

foreground = "#f8dcc0"
dark_foreground = "#9E9E9E"
light_foreground = "#C7C7D4"
bright_foreground = "#ffffff"

red = "#a02733"
yellow = "#ce7837"
orange = "#E19773"
green = "#549235"
cyan = "#26977b"
blue = "#2b53ab"
magenta = "#665993"
brown = "#A86D3B"

bright_red = "#fc5f5a"
bright_yellow = "#efc11a"
bright_green = "#9eff6e"
bright_cyan = "#5afcd4"
bright_blue = "#1997c6"
bright_magenta = "#b283f8"
